import { NextResponse } from "next/server"
import { analyzeDeal } from "@/lib/analyzer"
import type { AnalyzerInput } from "@/lib/types"

/**
 * Deal analysis endpoint.
 *
 * Right now this returns a transparent rule-based ESTIMATE. When a real AI /
 * valuation provider is connected, branch on an env flag (e.g. AI_GATEWAY_API_KEY
 * or a dedicated valuation key) and return `source: "ai"` with `isEstimate: false`.
 * The response shape (DealAnalysis) stays identical so the UI does not change.
 */
export async function POST(request: Request) {
  let input: AnalyzerInput
  try {
    input = (await request.json()) as AnalyzerInput
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 })
  }

  const aiConnected = Boolean(process.env.DEALFLOW_AI_API_KEY)

  // TODO: when `aiConnected`, call the AI/valuation provider here and map its
  // response into the DealAnalysis shape. Until then we always use the heuristic.
  const analysis = analyzeDeal(input)

  return NextResponse.json({
    analysis,
    aiConnected,
    notice: aiConnected
      ? undefined
      : "Estimate generated by DealFlow's rule-based model. Connect an AI/valuation API for live comps.",
  })
}
