import { analyzeDeal, temperatureFromScore } from "./analyzer"
import type { Buyer, Lead } from "./types"

/**
 * Realistic demo leads shown only when the user has no saved leads.
 * These are flagged in the UI as "Sample data" and are read-only until the
 * user adds their own first lead.
 */
function makeSampleLead(
  partial: Omit<Lead, "analysis" | "temperature" | "createdAt" | "updatedAt">,
): Lead {
  const analysis = analyzeDeal({
    arv: partial.estimatedValue,
    askingPrice: partial.askingPrice,
    sqft: partial.sqft,
    condition: partial.condition,
    motivationSignals: partial.motivationSignals,
    timeline: partial.timeline,
  })
  const now = new Date().toISOString()
  return {
    ...partial,
    analysis,
    temperature: temperatureFromScore(analysis.score),
    createdAt: now,
    updatedAt: now,
  }
}

export const SAMPLE_LEADS: Lead[] = [
  makeSampleLead({
    id: "sample-1",
    sellerName: "Sarah M.",
    phone: "(727) 555-0142",
    address: "1427 Bay Pine Dr",
    city: "Clearwater",
    state: "FL",
    propertyType: "Single family",
    beds: 3,
    baths: 2,
    sqft: 1580,
    yearBuilt: 1978,
    condition: "moderate",
    askingPrice: 205000,
    estimatedValue: 285000,
    motivation: "Going through a divorce and needs to sell quickly.",
    motivationSignals: ["Divorce", "Relocation"],
    timeline: "asap",
    stage: "offer",
  }),
  makeSampleLead({
    id: "sample-2",
    sellerName: "James R.",
    phone: "(727) 555-0198",
    address: "8021 Lake Fern Ln",
    city: "Largo",
    state: "FL",
    propertyType: "Single family",
    beds: 4,
    baths: 2,
    sqft: 1820,
    yearBuilt: 1985,
    condition: "light",
    askingPrice: 240000,
    estimatedValue: 300000,
    motivation: "Property has been vacant for 8 months, tired of upkeep.",
    motivationSignals: ["Vacant", "Tired landlord"],
    timeline: "30days",
    stage: "qualified",
  }),
  makeSampleLead({
    id: "sample-3",
    sellerName: "Maria T.",
    phone: "(813) 555-0111",
    address: "3315 Oak Crest Ave",
    city: "Tampa",
    state: "FL",
    propertyType: "Single family",
    beds: 3,
    baths: 1,
    sqft: 1240,
    yearBuilt: 1962,
    condition: "heavy",
    askingPrice: 150000,
    estimatedValue: 245000,
    motivation: "Inherited the home, lives out of state, wants it gone.",
    motivationSignals: ["Inherited", "Major repairs"],
    timeline: "flexible",
    stage: "qualified",
  }),
  makeSampleLead({
    id: "sample-4",
    sellerName: "Devon P.",
    phone: "(727) 555-0173",
    address: "605 Harbor View Ct",
    city: "Pinellas Park",
    state: "FL",
    propertyType: "Townhouse",
    beds: 2,
    baths: 2,
    sqft: 1100,
    yearBuilt: 1999,
    condition: "light",
    askingPrice: 185000,
    estimatedValue: 220000,
    motivation: "Absentee owner, open to offers.",
    motivationSignals: ["Relocation"],
    timeline: "90days",
    stage: "new",
  }),
  makeSampleLead({
    id: "sample-5",
    sellerName: "Estate of R. Cole",
    phone: "(813) 555-0155",
    address: "77 Palm Ridge Rd",
    city: "Brandon",
    state: "FL",
    propertyType: "Single family",
    beds: 3,
    baths: 2,
    sqft: 1650,
    yearBuilt: 1990,
    condition: "moderate",
    askingPrice: 210000,
    estimatedValue: 290000,
    motivation: "Estate sale, heirs behind on the property taxes.",
    motivationSignals: ["Inherited", "Tax liens", "Behind on payments"],
    timeline: "asap",
    stage: "contract",
  }),
  makeSampleLead({
    id: "sample-6",
    sellerName: "Gulf Rentals LLC",
    address: "210 Sunset Ave",
    city: "St. Petersburg",
    state: "FL",
    propertyType: "Duplex",
    beds: 4,
    baths: 2,
    sqft: 2100,
    yearBuilt: 1972,
    condition: "moderate",
    askingPrice: 195000,
    estimatedValue: 275000,
    motivation: "Tired landlord exiting the market.",
    motivationSignals: ["Tired landlord", "Vacant"],
    timeline: "30days",
    stage: "closed",
  }),
]

export const SAMPLE_BUYERS: Buyer[] = [
  {
    id: "buyer-1",
    name: "Gulf Coast Homes LLC",
    markets: ["Tampa", "Pinellas"],
    minBudget: 150000,
    maxBudget: 350000,
    strategy: "flip",
    propertyTypes: ["Single family", "Townhouse"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "buyer-2",
    name: "Sunline Capital",
    markets: ["Clearwater", "Largo"],
    minBudget: 100000,
    maxBudget: 250000,
    strategy: "rental",
    propertyTypes: ["Single family", "Duplex"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "buyer-3",
    name: "Bay Area Rehab",
    markets: ["Tampa Bay"],
    minBudget: 200000,
    maxBudget: 500000,
    strategy: "brrrr",
    propertyTypes: ["Single family", "Duplex", "Townhouse"],
    createdAt: new Date().toISOString(),
  },
]
